import type { Lead, ProjectForm } from "./types";

export const defaultLeadForm: Lead = {
  customer: {
    name: "",
    phone: "",
    email: "",
    shippingEmail: "",
    city: "",
    address: "",
    company: "",
    description: "",
  },
  property: {
    city: "",
    street: "",
    neighborhood: "",
    number: "",
    apt: "",
    parcel: "",
    subParcel: "",
    block: "",
    plot: "",
    propertyType: "",
    facadeType: "",
    factor: "",
    managerName: "",
  },
  payments: [{ amount: 0, description: "", plusVAT: false }],
  notes: "",
};

export const defaultProjectForm: ProjectForm = {
  name: "",
  description: "",
  status: "pre_visit",
  customer: {
    name: "",
    phone: "",
    email: "",
    city: "",
    shippingEmail: "",
    address: "",
  },
  address: {
    city: "",
    street: "",
    number: "",
    apt: "",
    neighborhood: "",
    block: "",
    parcel: "",
    subParcel: "",
    plot: "",
    lat: "",
    lng: "",
  },
  asset: {
    floor: "",
    rooms: "",
    areaSqm: "",
    propertyType: "",
    usage: "",
    purpose: "",
    appraisalDueDate: "",
    submissionDueDate: "",
    assessor: "",
    referrer: "",
  },
  visit: {
    contactRole: "",
    contactName: "",
    contactPhone: "",
    visitDate: "",
    visitTime: "",
    notes: "",
  },
  payments: [],
  notes: "",
};
